version: '3'
services:
  landing-page:
    build: ./landing-page
    volumes:
      - landing-page-static-content:/app/.next/static
      - landing-page-public:/app/public
    ports:
      - 3000:3000
  dashboard:
    build: ./dashboard
    volumes:
      - dashboard-public:/app/public
    ports:
      - 3001:3000
  api:
    build: ./api
    ports:
      - 3002:3000
volumes:
  landing-page-static-content:
  landing-page-public:
  dashboard-public: